version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ivorian-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ivorian_realty
    ports:
      - "27017:27017"
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - ivorian-dev-network

  # Redis Cache
  redis:
    image: redis:7.2-alpine
    container_name: ivorian-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - ivorian-dev-network

volumes:
  mongodb_dev_data:
  redis_dev_data:

networks:
  ivorian-dev-network:
    driver: bridge
